spring:
  datasource:
    url: "jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;MODE=MySQL"
    username: "sa"
    password: "sa"
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
interceptor:
  login-interceptor:
    excludeURIList:
      - "login"
      - "image"
      - "register"
    expireMinutes: 60
    secret: "abc123"
    headTokenKey: "token"

server:
  port: 8082
