spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/nero_accounting?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
interceptor:
  login-interceptor:
    excludeURIList:
      - "login"
      - "image"
      - "register"
    expireMinutes: 60
    secret: "abc123"
    headTokenKey: "token"

server:
  port: 8082

image:
  upload:
    real-prefix-path:
      "D:/image/"
    virtual-prefix-path:
      "http://localhost:8082/image/"
